In [1]:
#Import packages

In [ ]:
import pandas as pd
import numpy as np
from numpy.linalg import inv


In [ ]:
#Downloading the dataset

In [28]:
df = pd.read_csv("car_fuel_efficiency.csv")

In [20]:

pd.__version__
     

'2.2.2'

In [ ]:
#Loading the dataset as a DataFrame

In [42]:
df_car = pd.read_csv("car_fuel_efficiency.csv")
df_car.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [ ]:
#Q2. Records count
#How many records are in the dataset?

In [46]:
print(f"This dataset contain {df_car.shape[0]}")

This dataset contain 9704


In [ ]:
#Q3. Fuel types
#How many fuel types are presented in the dataset?

In [52]:
print(f"There are {df.fuel_type.nunique()} types of fuel in the dataset")

There are 2 types of fuel in the dataset


In [ ]:
#Q4. Missing values
#How many columns in the dataset have missing values?

In [54]:
print(f"There are {sum(df.isna().sum()>0)} columns with missing values")

There are 4 columns with missing values


In [ ]:
#Q5. Max fuel efficiency
#What's the maximum fuel efficiency of cars from Asia?

In [74]:
print(f"The maximum fuel efficiency is {df["fuel_efficiency_mpg"].max()}")

The maximum fuel efficiency is 25.96722204888372


In [ ]:
#Q6. Median value of horsepower
#Find the median value of the horsepower column in the dataset.
#Next, calculate the most frequent value of the same horsepower column.
#Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
#Now, calculate the median value of horsepower once again.

In [80]:
print(f"Median  value of horsepower:  {df.horsepower.median()}")
print(f"Mode of horsepower column:  {df.horsepower.mode().iloc[0]}")
horsepower_filled = df.horsepower.fillna(df.horsepower.mode().iloc[0])

print(f"Median  of horse filled:  {Screen_filled.median()}")


print("No it hasn't changed") if df.horsepower.median() == Screen_filled.median() else print("Yes it has changed")

Median  value of horsepower:  149.0
Mode of horsepower column:  152.0
Median  of horse filled:  152.0
Yes it has changed


In [ ]:
#Q7. Sum of weights
#Select all the cars from Asia
#Select only columns vehicle_weight and model_year
#Select the first 7 values
#Get the underlying NumPy array. Let's call it X.
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#Invert XTX.
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#What's the sum of all the elements of the result?

In [86]:
print(f"Sum  of weights :  {df.vehicle_weight.sum()}")

Sum  of weights :  29124430.759692904


In [220]:
#1
df_car[df_car['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [242]:
#2
df_car.loc[df_car['origin'] == 'Asia', ['vehicle_weight', 'model_year']]

     

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [ ]:
#Select the first 7 values

In [260]:
#df_car.loc[df_car['origin'] == 'Asia', ['vehicle_weight', 'model_year']].head(7)

In [262]:
 #X = df_car.loc[df_car['origin'] == 'Asia', ['vehicle_weight', 'model_year']].to_numpy()
#X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       ...,
       [2545.07013932, 2012.        ],
       [3107.42781965, 2005.        ],
       [2908.04347736, 2005.        ]])

In [264]:
#X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, ..., 2545.07013932,
        3107.42781965, 2908.04347736],
       [2016.        , 2010.        , 2007.        , ..., 2012.        ,
        2005.        , 2005.        ]])

In [266]:
#XTX = np.matmul(X.T, X)
#XTX

array([[3.01651358e+10, 1.96349896e+10],
       [1.96349896e+10, 1.31377985e+10]])

In [268]:
#XTX_inv = inv(XTX)
#XTX_inv

array([[ 1.21977675e-09, -1.82300740e-09],
       [-1.82300740e-09,  2.80067709e-09]])

In [270]:
#y = np.array([1100, 1300, 800, 900, 1000, 1100,1200])
#y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [274]:
X = (
    df_car.loc[df_car['origin'] == 'Asia', ['vehicle_weight', 'model_year']]
         .head(7)
         .to_numpy(dtype=float)      
)

# 5) XTX and its inverse
XTX = X.T @ X
try:
    XTX_inv = np.linalg.inv(XTX)      
except np.linalg.LinAlgError:
    XTX_inv = np.linalg.pinv(XTX)     

# 6) y array
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200], dtype=float)

# 7) w = (XTX^-1) * X.T * y
w = XTX_inv @ X.T @ y

# 8) Sum of all elements of w
result = w.sum()
print("Sum of elements in w:", result)

Sum of elements in w: 0.5187709081074007
